# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
version: 2

project_name: ght

before:
  hooks:
    - go mod tidy

builds:
  - id: ght
    main: ./cmd/ght
    binary: ght
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w

archives:
  - id: ght
    builds:
      - ght
    name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"
    format: tar.gz
    files:
      - README.md

checksum:
  name_template: checksums.txt
  algorithm: sha256

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^chore:"
      - Merge pull request
      - Merge branch
